### ISSUE TITLE
Check for realpath in polyglot release 

### ISSUE THREAD

**Issue by mpkorstanje** [cucumber/.github#16]
>  * The `realpath` command. On MacOS you can install this with `brew install coreutils`

Which proces uses this? Documenting it here will just have the information go stale.

If it is polyglot release I think this should be documented with polyglot release. Or rather polyglot release should check and let people know they should install it.

_Originally posted by @mpkorstanje in https://github.com/cucumber/.github/pull/10#discussion_r994286567_

**Comment by mpkorstanje** [comment]
I'll move this when not on mobile.

**Comment by mpkorstanje** [comment]
We already test for realpath in polyglot-release.

https://github.com/cucumber/polyglot-release/blob/main/polyglot-release#L508

@aslakhellesoy what exactly was the situation you are trying to solv?

**Comment by aslakhellesoy** [comment]
I don’t remember @mpkorstanje
