### ISSUE TITLE
Simplify the PR template

### ISSUE THREAD

**Issue by aslakhellesoy** [cucumber/.github#7]
People don’t fill it in properly anyway and the number of emoji hurts my eyes.

![E9030529-B38A-4ED1-891A-9FAAE3AA6328](https://user-images.githubusercontent.com/1000/168640734-6853e753-9f38-4958-a1fe-76eb748c148b.png)

**Comment by mpkorstanje** [comment]
> People don’t fill it in properly anyway

But when they do it's useful.

**Comment by aurelien-reeves** [comment]
I totally agree with Aslak:

- emojis are too much here (and yet I am a huge user of emojis)
- there is too much text: it needs to be simplified (we could still keep the same sections)
- there is a feature in github which shows progress bar regarding the checkboxes in a PR description. But the actual template do not take benefit of this: all the checkboxes in the template do not act as a todo-list

**Comment by mattwynne** [comment]
Disagree. Most people do fill it in, and the information they provide is useful.

This PR text is the result of several iterations I've made, based on watching real contributors trying to make their first pull requests. The emojis add some warmth and make the process less daunting for them.
