### ISSUE TITLE
Document how to update python dependencies

### ISSUE THREAD

**Issue by aslakhellesoy** [cucumber/.github#8]
### 🤔 What's the problem you're trying to solve?

Make a release of Cucumber Expressions with as many dependencies as possible updated.

### ✨ What's your proposed solution?

Document how to do it for python.

### ⛏ Have you considered any alternatives or workarounds?

Not sure what to make of this: https://github.com/python-poetry/poetry/issues/461

### 📚 Any additional context?

I think some projects are using `pyproject.toml` while others are using `requirements.txt`.
Can we settle on one? In the meanwhile, what's the correct way to update dependencies in both?

Amy suggestions @jenisys @jsa34 @brasmusson

**Comment by mattwynne** [comment]
What's this issue doing in this repo? Should we move it to cucumber/cucumber-expressions?

**Comment by mpkorstanje** [comment]
@mattwynne I think he's following the release instructions that say to update the depencies before release. I usually don't bother with that. It's what renovate is for.

Also, updating depencies just before you release is asking for problems. Making a release is - assuming the process works - an activity wich needs a fixed amount of time. Updating depencies is an unbounded activity.

I would suggest moving the update dependency step to the post release process. I would also suggest adding a note to investigate why Renovate didn't pick them up.

**Comment by jsa34** [comment]
Apologies - I missed this issue.

Ideally, we can add dependabot to make automated updates.

The package itself (not including tests) doesn't have any dependencies other than Python itself which is why it didn't even cross my mind.

There is a "manual" command that can be run to update dependencies across the board for Poetry projects, but with pyproject.toml files supported by dependabot, perhaps that's a better way to go.

**Comment by mpkorstanje** [comment]
> Ideally, we can add/fix renovate to make automated updates for the pyproject.toml and poetry.lock files: [here](https://docs.renovatebot.com/modules/manager/poetry/) (Not sure if it should be enabled by default)

Looking at the history it looks like Renovate has picked up Poetry and PyProject files just fine:

- https://github.com/cucumber/cucumber-expressions/commits/main/python/pyproject.toml
- https://github.com/cucumber/cucumber-expressions/commits/main/python/poetry.lock

> We should also probably use a common packaging solution across Python projects, too - that's probably my fault for sticking Poetry in the mix, but happy to rework to whatever a common consensus is :)

Would be nice, but for the current discussion having more then 1 solution is not a problem. Renovate supports both.

**Comment by jsa34** [comment]
Ah - apologies - I didn't even look.  I just assumed from the message that Renovate hadn't.

Teaches me to make assumptions!
________________________________
